insert into type(typename)
values ('sensation'),
       ('fantasy'),
       ('narration'),
       ('challenge'),
       ('partnership'),
       ('opening'),
       ('self-expression'),
       ('acceptance'),
       ('completion'),
       ('gloat'),
       ('donation'),
       ('humor'),
       ('opportunity'),
       ('surprise'),
       ('fear'),
       ('victory');


insert into words(word, type_id)
values ('elegant', 1),
       ('stylish', 1),
       ('graceful', 1),
       ('beautiful', 1),
       ('music', 1),
       ('aesthetics', 1),
       ('esthetics', 1),
       ('sensation', 1),
       ('sound', 1),
       ('sight', 1),
       ('fantasy', 2),
       ('imagination', 2),
       ('idea', 2),
       ('performance', 2),
       ('representation', 2),
       ('fairy', 2),
       ('magical', 2),
       ('alternative', 2),
       ('powers', 2),
       ('power', 2),
       ('drama', 3),
       ('dramaturgy', 3),
       ('dramatic', 3),
       ('theatrical', 3),
       ('narration', 3),
       ('story', 3),
       ('narrative', 3),
       ('tale', 3),
       ('tales', 3),
       ('storyline', 3),
       ('script', 3),
       ('challenge', 4),
       ('hard', 4),
       ('decision', 4),
       ('complex', 4),
       ('complicated', 4),
       ('sophisticated', 4),
       ('puzzle', 4),
       ('conundrum', 4),
       ('difficult', 4),
       ('difficulty', 4),
       ('level', 4),
       ('friends', 5),
       ('friend', 5),
       ('cooperation', 5),
       ('collaboration', 5),
       ('partnership', 5),
       ('contribution', 5),
       ('friendship', 5),
       ('communication', 5),
       ('help', 5),
       ('cooperative', 5),
       ('joint', 5),
       ('online', 5),
       ('opened', 6),
       ('search', 6),
       ('scan', 6),
       ('study', 6),
       ('research', 6),
       ('investigation', 6),
       ('survey', 6),
       ('examination', 6),
       ('exploration', 6),
       ('opening', 6),
       ('discovery', 6),
       ('finding', 6),
       ('detection', 6),
       ('self-expression', 7),
       ('creation', 7),
       ('design', 7),
       ('making', 7),
       ('forming', 7),
       ('invention', 7),
       ('own', 7),
       ('self', 7),
       ('sharing', 7),
       ('immersive', 8),
       ('simulated', 8),
       ('artificial', 8),
       ('world', 8),
       ('believable', 8),
       ('sim', 8),
       ('immersed', 8),
       ('lore', 8),
       ('realistic', 8),
       ('simulation', 8),
       ('all', 9),
       ('every', 9),
       ('each', 9),
       ('entire', 9),
       ('completion', 9),
       ('accomplishment', 9),
       ('ending', 9),
       ('close', 9),
       ('finish', 9),
       ('end', 9),
       ('online', 10),
       ('competition', 10),
       ('contest', 10),
       ('meet', 10),
       ('match', 10),
       ('gloat', 10),
       ('justice', 10),
       ('punishment', 10),
       ('competitive', 10),
       ('players', 10),
       ('gift', 11),
       ('surprise', 11),
       ('astonishment', 11),
       ('amaze', 11),
       ('wonderment', 11),
       ('present', 11),
       ('surprising', 11),
       ('donation', 11),
       ('grant', 11),
       ('happiness', 11),
       ('humor', 12),
       ('humour', 12),
       ('satire', 12),
       ('irony', 12),
       ('fun', 12),
       ('comedy', 12),
       ('comical', 12),
       ('funny', 12),
       ('ridiculous', 12),
       ('joke', 12),
       ('laugh', 12),
       ('option', 13),
       ('options', 13),
       ('choice', 13),
       ('pick', 13),
       ('opportunity', 13),
       ('possibility', 13),
       ('variant', 13),
       ('various', 13),
       ('diversity', 13),
       ('variety', 13),
       ('surprise', 14),
       ('wonder', 14),
       ('astonishment', 14),
       ('amazement', 14),
       ('wonderment', 14),
       ('amaze', 14),
       ('surprised', 14),
       ('marvel', 14),
       ('miracle', 14),
       ('astonished', 14),
       ('amazed', 14),
       ('fear', 15),
       ('phobia', 15),
       ('terror', 15),
       ('thrill', 15),
       ('trembling', 15),
       ('awe', 15),
       ('shiver', 15),
       ('fearful', 15),
       ('scary', 15),
       ('spooky', 15),
       ('uncanny', 15),
       ('supernatural', 15),
       ('victory', 16),
       ('win', 16),
       ('low', 16),
       ('chances', 16),
       ('success', 16),
       ('little', 16),
       ('chance', 16),
       ('small', 16),
       ('hope', 16),
       ('effort', 16),
       ('attempts', 16),
       ('try', 16),
       ('trials', 16),
       ('attempt', 16);




select avg(count) from word_count where typename = 'self-expression';

select word from word_count where typename = 'self-expression' and count = 8;

select avg(count) from word_count where typename = 'fantasy';















