insert into type(typename)
values ('sensation'),
       ('fantasy'),
       ('narration'),
       ('challenge'),
       ('partnership'),
       ('opening'),
       ('self-expression'),
       ('acceptance'),
       ('completion'),
       ('gloat'),
       ('donation'),
       ('humor'),
       ('opportunity'),
       ('surprise'),
       ('fear'),
       ('victory');


insert into words(word, type_id)
values ('visuals', 1),
       ('aesthetics', 1),
       ('atmosphere', 1),
       ('sensory', 1),
       ('immersive', 1),
       ('tactile', 1),
       ('ambience', 1),
       ('sensation', 1),
       ('soundscape', 1),
       ('harmony', 1),
       ('escapism', 2),
       ('imagination', 2),
       ('creativity', 2),
       ('mythical', 2),
       ('alternate', 2),
       ('worldbuilding', 2),
       ('enchantment', 2),
       ('magic', 2),
       ('dreamlike', 2),
       ('surreal', 2),
       ('storytelling', 3),
       ('nonlinear', 3),
       ('intrigue', 3),
       ('subplot', 3),
       ('narration', 3),
       ('emotional', 3),
       ('narrative', 3),
       ('captivating', 3),
       ('unpredictable', 3),
       ('twist', 3),
       ('challenge', 4),
       ('skill', 4),
       ('mastery', 4),
       ('complexity', 4),
       ('complicated', 4),
       ('sophisticated', 4),
       ('puzzle', 4),
       ('tactics', 4),
       ('strategy', 4),
       ('difficult', 4),
       ('companionship', 5),
       ('companionship', 5),
       ('friendship', 5),
       ('teamwork', 5),
       ('social', 5),
       ('collaboration', 5),
       ('community', 5),
       ('support', 5),
       ('networking', 5),
       ('cooperative', 5),
       ('exploration', 6),
       ('discovery', 6),
       ('secrets', 6),
       ('uncharted', 6),
       ('hidden', 6),
       ('investigation', 6),
       ('insight', 6),
       ('curiosity', 6),
       ('opening', 6),
       ('finding', 6),
       ('expression', 7),
       ('creation', 7),
       ('customization', 7),
       ('artistry', 7),
       ('individuality', 7),
       ('personalization', 7),
       ('style', 7),
       ('originality', 7),
       ('design', 7),
       ('craft',7),
       ('acceptance', 8),
       ('inclusion', 8),
       ('artificial', 8),
       ('affiliation', 8),
       ('integration', 8),
       ('connection', 8),
       ('simulated', 8),
       ('believable', 8),
       ('realistic', 8),
       ('simulation', 8),
       ('completion', 9),
       ('accomplishment', 9),
       ('closure', 9),
       ('fulfillment', 9),
       ('resolution', 9),
       ('finality', 9),
       ('achievement', 9),
       ('ending', 9),
       ('conclusion ', 9),
       ('milestone', 9),
       ('gloat', 10),
       ('retribution', 10),
       ('contest', 10),
       ('payback', 10),
       ('justice', 10),
       ('reckoning', 10),
       ('triumph', 10),
       ('punishment', 10),
       ('competitive', 10),
       ('competition', 10),
       ('gift', 11),
       ('gifting', 11),
       ('delight', 11),
       ('sharing', 11),
       ('contribution', 11),
       ('present', 11),
       ('altruism', 11),
       ('donation', 11),
       ('grant', 11),
       ('kindness', 11),
       ('humor', 12),
       ('wit', 12),
       ('amusement ', 12),
       ('laughter', 12),
       ('comedy', 12),
       ('joke', 12),
       ('ridiculous', 12),
       ('satire', 12),
       ('hilarity', 12),
       ('comical',12),
       ('possibility', 13),
       ('choice', 13),
       ('potential', 13),
       ('options', 13),
       ('alternatives', 13),
       ('opportunity', 13),
       ('flexibility', 13),
       ('variant', 13),
       ('diversity', 13),
       ('variety', 13),
       ('surprise', 14),
       ('unexpected ', 14),
       ('revelation', 14),
       ('astonishment', 14),
       ('marvel', 14),
       ('unpredictable', 14),
       ('startling', 14),
       ('shock', 14),
       ('miracle', 14),
       ('unanticipated', 14),
       ('thrill', 15),
       ('excitement', 15),
       ('intensity', 15),
       ('thrill', 15),
       ('suspense', 15),
       ('anticipation', 15),
       ('fear', 15),
       ('terror', 15),
       ('scary', 15),
       ('tension', 15),
       ('overcoming', 16),
       ('victory', 16),
       ('conquest', 16),
       ('perseverance', 16),
       ('resilience', 16),
       ('success', 16),
       ('effort', 16),
       ('attempts', 16),
       ('trials', 16),
       ('attempt', 16);

select word from word_count where typename = 'sensation' and count > 5 and count < 9;


















